# Generated by Django 5.1.6 on 2025-03-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo_Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=600)),
                ("time_created", models.DateTimeField(auto_now_add=True)),
                ("task_completed", models.BooleanField(default=False)),
            ],
        ),
    ]
