# Generated by Django 5.1.6 on 2025-03-04 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Todo_Item",
            new_name="TodoItem",
        ),
    ]
