# Generated by Django 5.1.6 on 2025-03-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_todo_item_todoitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="description",
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
