# Generated by Django 5.1.7 on 2025-03-06 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_todoitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
